### PR TITLE
🛠️  refactor: generator and lib scripts, re-introduced cli

### PR DESCRIPTION
**Pull request by webcoderz**

### CODE REVIEW

**Comment by Jon-Becker** [comment]
Hey! I'll try to review this weekend. Thank you for contributing <3

**Comment by webcoderz** [comment]
You're welcome, there's a slight bug somewhere in the PIL compilation stuff where it's not transposing the layers.. I haven't found it yet but it's somewhere in the in the checking and merging layers part

**Comment by webcoderz** [comment]
ok found the bug. fixed

**Comment by webcoderz** [comment]
Also if you're interested I have made further updates on generating directories and it basically makes a project/ dir where it puts the trait layers etc dirs into a project/{project_name}/* dir for better organization

**Comment by webcoderz** [comment]
also wasnt sure which CID update code worked.. i so added both for good measure

**Review by Jon-Becker — CHANGES_REQUESTED** [review]
Repo is so old I dont even have unit tests / CI/CD setup.

I'll tackle this tonight and then we can merge this puppy.

Thank you!

**Pull request merged**
